package greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hl.htk_customer.greendao.FunctionTypeEntity;
import com.hl.htk_customer.greendao.User;

import greendao.FunctionTypeEntityDao;
import greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig functionTypeEntityDaoConfig;
    private final DaoConfig userDaoConfig;

    private final FunctionTypeEntityDao functionTypeEntityDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        functionTypeEntityDaoConfig = daoConfigMap.get(FunctionTypeEntityDao.class).clone();
        functionTypeEntityDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        functionTypeEntityDao = new FunctionTypeEntityDao(functionTypeEntityDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(FunctionTypeEntity.class, functionTypeEntityDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        functionTypeEntityDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public FunctionTypeEntityDao getFunctionTypeEntityDao() {
        return functionTypeEntityDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
